# .github/workflows/quarto-publish.yml
# ────────────────────────────────────────────────────────────
# Buduje i publikuje stronę Quarto (HTML) na gałąź gh‑pages.
# Działa dla projektów R Markdown, Python oraz czysto .qmd.

name: quarto-publish

on:
  push:
    branches: [ main, master ]      # render przy każdym push do głównej gałęzi
  workflow_dispatch:                # pozwala uruchomić ręcznie z UI

permissions:
  contents: write                   # potrzebne, by wypchnąć do gh‑pages

jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      # 1) Sklonuj repo
      - uses: actions/checkout@v4

      # 2) Zainstaluj Quarto CLI (automatycznie dobiera najnowszą wersję)
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          install-dependencies: true    # pobiera pandoc + typowe rozszerzenia

      # 3) (opcjonalnie) zainstaluj R i pakiety, jeśli masz chunki R
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true         # szybsze binarki Posit Public

      - name: Install R packages needed by docs
        run: |
          install.packages(c("tidyverse", "knitr", "gt"))
        shell: Rscript {0}

      # 4) Render całej strony do domyślnego folderu _site/
      - name: Render Quarto project
        run: quarto render

      # 5) Deploy do gałęzi gh‑pages (GitHub Pages)
      - name: Publish to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site                # katalog wygenerowany przez Quarto
          publish_branch: gh-pages          # docelowa gałąź
          keep_files: true                  # nie kasuj ręcznie wgranych plików
